config/routes.rb
Rails.application.routes.draw do
  resources :stories

  root 'stories#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get  '/signup' => 'users#new'
  post '/users' => 'users#create'

  get  '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get  '/logout' => 'sessions#destroy'

  mount Shrine::DownloadEndpoint => "/attachments"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image_uploader.rb
class ImageUploader < Shrine
  # plugins and uploading logic
    include ImageUploader[:image]
end

app/models/story.rb
class Story < ApplicationRecord
  belongs_to :created_by, class_name: "User"
  include ImageUploader[:image]
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def authorize!
    redirect_to login_path unless logged_in?
  end

  def logged_in?
    !!current_user
  end
  helper_method :logged_in?

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  # logging in (show the login form)
  def new

  end

 # handle the post from the login form/page
  def create
    email = params[:email]
    password = params[:password]

  # find the user by their email
    user = User.find_by(email: email)

    if user && user.authenticate(password)
      session[:user_id] = user.id

      redirect_to root_path
    else
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil

    redirect_to stories_path
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_action :authorize!, except: [:stories, :show]

  # GET /stories
  def index
    @stories = Story.all.order(:created_at => "DESC")
  end

  # GET /stories/1
  def show
    @story = Story.find(params[:id])
  end

  # GET /stories/new
  def new
    @story = Story.new
  end

  # GET /stories/1/edit
  def edit
    @story = Story.find(params[:id])
  end

  # POST /stories
  def create
    @story = Story.new(story_params)
    @story.created_by = current_user

    if @story.save
      redirect_to @story, notice: 'Story was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /stories/1
  def update
    @story = Story.find(params[:id])
    if @story.update(story_params)
      redirect_to @story, notice: 'Story was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /stories/1
  def destroy
    @story = Story.find(params[:id])
    @story.destroy
    redirect_to stories_url, notice: 'Story was successfully destroyed.'
  end

  private
    # Only allow a trusted parameter "white list" through.
    def story_params
      params.require(:story).permit(:number, :title, :email, :link, :image)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to stories_path
    else
      render :new
    end
  end

private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>
    <%= Rails.application.class.parent_name %>
  </title>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %>
  <![endif]-->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="controller-<%= controller_name%> action-<%= action_name%>">
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to root_path, class: "navbar-brand" do %>
          | TIY media |
        <% end %>
      </div>

      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li class="active"><%= link_to "Home", root_path %></li>
        </ul>
        <% if logged_in? %>
          <ul class="nav navbar-nav navbar-right">
            <li>
              <p class="navbar-text">| Logged in: <%= current_user.name %> |</p>
            </li>
            <li>
              <%= link_to "| Logout |", logout_path %>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li>
              <%= link_to "| New Story |", new_story_path %>
            </li>
          </ul>
        <% else %>
          <ul class="nav navbar-nav navbar-right">
            <li>
              <%= link_to "| Sign up |", signup_path %>
            </li>
            <li>
              <%= link_to "| Log in |", login_path %>
            </li>
          </ul>
        <% end %>
      </div>
    </div>

  </nav>
  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, class: "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do %>
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <%= msg %>
      <% end %>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>

app/views/stories/_form.html.erb
<%= form_for(@story, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @story.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@story.errors.count, "error") %> prohibited this story from being saved:</h4>

      <ul>
      <% @story.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
          <%= f.label :title, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_field :title, class: "form-control" %>
      </div>
  </div>

  <div class="form-group">
    <%= f.label :link, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_field :link, class: "form-control" %>
      </div>
  </div>

  <div class="form-group">
    <%= f.label :email, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_field :email, class: "form-control" %>
      </div>
  </div>

  <div class="form-group">
    <%= f.label :image_url, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.hidden_field :image, value: @story.cached_image_data %>
        <%= f.file_field :image %>
      </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-success" %>
    </div>
  </div>
<% end -%>

app/views/stories/edit.html.erb
<div class="page-header">
  <%= link_to stories_path, class: 'btn btn-success' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @story, class: 'btn btn-success' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing story</h1>
</div>

<%= render 'form' %>

app/views/stories/index.html.erb
<div class="">
  <h3 Listing>| Iron News |</h3>
</div>
<hr>

<ul class="list-group">
  <%- @stories.each_with_index do |story, index| %>
    <li class="list-group-item">
      <div class="media">
        <div class="media-left">
          <a href="#">
            <img class="media-object" src="<%= story.image_url %>" height="72" width="72">
          </a>
        </div>
        <div class="media-body">
          <h4 class="media-heading"><small><%= index + 1 %></small>.  <%= link_to story.title, story.link %></h4>
          <%= story.email %>
          <ul>
            <li>| posted on: <small><%= story.created_at %></small> |</li>
          </ul>
          <div class="pull-right">
            <%= link_to story do %>
              <button type="button" class="btn-group btn-default btn-xs">View <span class="glyphicon glyphicon-home" aria-hidden="true"></span></button>
            <% end %>
            <% if logged_in? %>
              <%= link_to edit_story_path(story) do %>
                <button type="button" class="btn-group btn-default btn-xs">Edit</button>
              <% end %>
            <% end %>
            <% if logged_in? %>
              <%= link_to story, method: :delete, data: { confirm: 'Are you sure?' } do %>
                <button type="button" class="btn-group btn-default btn-xs">Delete <span class="glyphicon glyphicon-remove" aria-hidden="true"></span></button>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </li>
  <% end %>
</ul>

app/views/stories/new.html.erb
<div class="page-header">
  <%= link_to stories_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New story</h1>
</div>

<%= render 'form' %>

app/views/stories/show.html.erb
<div class="page-header">
  <%= link_to stories_path, class: 'btn btn-success' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_story_path(@story), class: 'btn btn-success' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Article display</h1>
</div>

<dl class="dl-horizontal">
  <dt>Title:</dt>
  <dd><%= @story.title %></dd>

  <dt>Link:</dt>
  <dd><%= @story.link %></dd>

  <dt>Email:</dt>
  <dd><%= @story.email %></dd>

  <dt>Image:</dt>
  <dd><%= image_tag(@story.image_url, size: "350") %></dd>

</dl>

app/views/users/new.html.erb
<!-- Path: app/views/users/new.html.erb -->

<div class="page-header">
  <h1>Signup!</h1>
</div>

<%= form_for(@user, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <div class="form-group">
    <%= f.label :name, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :email, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :email, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :password, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.password_field :password, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :password_confirmation, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.password_field :password_confirmation, class: "form-control" %>
    </div>
  </div>
  <%= f.submit "Submit", class: "btn btn-primary" %>
<% end %>